version: "3.9"

volumes:
  webapp-volume:

services:
  backend:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: poetry run flask run
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main:app
      - FLASK_ENV=production
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0

  conversionrunner:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: poetry run python3 ./conversionrunner.py
    depends_on:
      - backend

  segmentrunner:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: poetry run python3 ./segmentrunner.py
    depends_on:
      - backend

  meshrunner:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: poetry run python3 ./meshrunner.py
    depends_on:
      - backend
