volumes:
  ml4paleo-webapp-volume:
    driver: local
    driver_opts:
      device: '/home/ubuntu/ml4paleo-webapp-volume/'
      o: 'bind'
      type: none

services:
  backend:
    image: ml4paleo
    build: .
    volumes:
      - ml4paleo-webapp-volume:/ml4paleo/webapp/volume
    entrypoint: gunicorn --bind :5000 --access-logfile - --error-logfile - --log-level info main:app --timeout 300
    ports:
      - "5000:5000"
    restart: always

  conversionrunner:
    image: ml4paleo
    build: .
    volumes:
      - ml4paleo-webapp-volume:/ml4paleo/webapp/volume
    entrypoint: python3 ./conversionrunner.py
    depends_on:
      - backend
    restart: always

  segmentrunner:
    image: ml4paleo
    build: .
    volumes:
      - ml4paleo-webapp-volume:/ml4paleo/webapp/volume
    entrypoint: python3 ./segmentrunner.py
    depends_on:
      - backend
    restart: always

  meshrunner:
    image: ml4paleo
    build: .
    volumes:
      - ml4paleo-webapp-volume:/ml4paleo/webapp/volume
    entrypoint: python3 ./meshrunner.py
    depends_on:
      - backend
    restart: always
