version: "3.9"

volumes:
  webapp-volume:

services:
  backend:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: gunicorn --bind :5000 --access-logfile - --error-logfile - --log-level info main:app --timeout 300
    ports:
      - "5000:5000"

  conversionrunner:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: python3 ./conversionrunner.py
    depends_on:
      - backend

  segmentrunner:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: python3 ./segmentrunner.py
    depends_on:
      - backend

  meshrunner:
    image: ml4paleo
    build: .
    volumes:
      - webapp-volume:/ml4paleo/webapp/volume
    entrypoint: python3 ./meshrunner.py
    depends_on:
      - backend
